name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: wifi creds #temp fix to test if firmware builds
        run: touch ./include/wifi_secrets.h
      - name: add dummy stuff
        run: |
          cat <<-EOF > ./include/wifi_secrets.h
            #ifndef WIFI_SECRETS_H
            #define WIFI_SECRETS_H
  
            #define WIFI_SSID ""
            #define WIFI_PASSWORD ""
            #define CLIENT_NAME ""
            #define CLIENT_KEY ""
  
            #endif //WIFI_SECRETS_H
          EOF
      - name: Build PlatformIO Project
        run: pio run
