
name: Build and Release Firmware

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: PlatformIO Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: wifi creds #temp fix while bluetooth onboarding isn't implemented
        run: touch ./include/wifi_secrets.h
      - name: add dummy stuff
        run: |
          cat <<-EOF > ./include/wifi_secrets.h
            #ifndef WIFI_SECRETS_H
            #define WIFI_SECRETS_H

            #define WIFI_SSID ""
            #define WIFI_PASSWORD ""
            #define CLIENT_NAME ""
            #define CLIENT_KEY ""

            #endif //WIFI_SECRETS_H
          EOF
      - name: Compile firmware for all environments
        run: pio run

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload firmware for seeed_xiao_esp32c3
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .pio/build/seeed_xiao_esp32c3/firmware.bin
          asset_name: seeed_xiao_esp32c3_firmware.bin
          asset_content_type: application/octet-stream

      - name: Set asset name for seeed_xiao_esp32c3
        run: |
          asset_name=$(echo ${{ github.ref_name }} | sed 's/v//g' | sed 's/\./-/g')_v3.bin
          echo "asset_name=${asset_name}" >> $GITHUB_ENV

      - name: Upload firmware for custom-board-v4
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .pio/build/custom-board-v4/firmware.bin
          asset_name: custom-board-v4_firmware.bin
          asset_content_type: application/octet-stream

      - name: Set asset name for custom-board-v4
        run: |
          asset_name=$(echo ${{ github.ref_name }} | sed 's/v//g' | sed 's/\./-/g')_v4.bin
          echo "asset_name=${asset_name}" >> $GITHUB_ENV

      - name: Upload firmware for custom-board-v5
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .pio/build/custom-board-v5/firmware.bin
          asset_name: custom-board-v5_firmware.bin
          asset_content_type: application/octet-stream

      - name: Set asset name for custom-board-v5
        run: |
          asset_name=$(echo ${{ github.ref_name }} | sed 's/v//g' | sed 's/\./-/g')_v5.bin
          echo "asset_name=${asset_name}" >> $GITHUB_ENV